version: '3.8'
services:
  nginx:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.nginx
    volumes:
      - certbot-data:/etc/letsencrypt
      - certbot-logs:/var/log/letsencrypt
      - saved-nginx-conf:/etc/nginx/conf.d
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - "frontend"
      - "backend"
      - "celery"
    networks:
      - cuapi
    env_file:
      - .env
    image: nathanngc/nginx:latest
  backend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.backend
    image: nathanngc/backend:latest
    env_file:
      - .env
    environment:
      POSTGRES_HOST: "db"
      POSTGRES_DB: "cuapi"
      REDIS_HOST: "redis"
    ports:
      - "3969:3969"
    networks:
      - cuapi
    volumes:
      - .:/app
    depends_on:
      - "db"
    command: ["./wait-for-it.sh", "db:5432", "--timeout=60", "--", "gunicorn", "--bind", "0.0.0.0:3969", "api:app"]
  frontend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.frontend
    env_file:
      - .env
    ports:
      - "3959:3959"
    networks:
      - cuapi
    image: nathanngc/frontend:latest
  db:
    image: postgres:13
    env_file:
      - .env
    environment:
      POSTGRES_HOST: "db"
      POSTGRES_DB: "cuapi"
    ports:
      - "5432:5432"
    networks:
      - cuapi
    volumes:
      - db-data:/var/lib/postgresql/data
  redis:
    image: redis/redis-stack:6.2.6-v7
    ports:
      - "6379:6379"
    env_file:
      - .env
    networks:
      - cuapi
  celery:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.celery
    env_file:
      - .env
    environment:
      IS_BEAT: "true"
      REDIS_HOST: "redis"
    depends_on:
      - "redis"
      - "backend"
    volumes:
      - .:/app
    networks:
      - cuapi
    command: ["./wait-for-it.sh", "redis:6379", "--timeout=60", "--", "python3", "-m", "celery", "--app=tasks", "beat", "--loglevel=info"]
    image: nathanngc/celery:latest
  localworker:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.celery
    env_file:
      - .env
    environment:
      IS_BEAT: "false"
      REDIS_HOST: "redis"
      LOCAL_WORKER: "true"
      POSTGRES_HOST: "db"
      POSTGRES_DB: "cuapi"
    depends_on:
      - "redis"
      - "backend"
    volumes:
      - .:/app
    networks:
      - cuapi
    command: ["./wait-for-it.sh", "redis:6379", "--timeout=60", "--", "python3", "-m", "celery", "--app=tasks", "worker", "-Q", "localwrite", "--loglevel=info", "--concurrency=1"]
    image: nathanngc/localworker:latest
volumes:
  db-data:
  certbot-data:
  certbot-logs:
  saved-nginx-conf:
networks:
  cuapi:
    driver: bridge
