apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: cuapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: ngcnathan/backend:latest
        command: ["./wait-for-it.sh", "neo4j:7687", "--", "/backend"]
        imagePullPolicy: Always
        ports:
        - containerPort: 3969
        envFrom:
        - configMapRef:
            name: cuapi-env
        resources:
          limits:
            cpu: "2"
            memory: "4Gi"
          requests:
            cpu: "100m"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3969
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: cuapi
spec:
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 3969
    targetPort: 3969
  type: ClusterIP