apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: cuapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: ngcnathan/frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3959
        envFrom:
        - configMapRef:
            name: cuapi-env
        volumeMounts:
        - name: frontend-volume
          mountPath: /usr/share/nginx/html
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
      volumes:
      - name: frontend-volume
        persistentVolumeClaim:
          claimName: frontend-data
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: cuapi
spec:
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 3959
    targetPort: 3959
  type: ClusterIP