apiVersion: apps/v1
kind: Deployment
metadata:
  name: neo4j
  namespace: cuapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: neo4j
  template:
    metadata:
      labels:
        app: neo4j
    spec:
      containers:
      - name: neo4j
        image: neo4j:latest
        ports:
        - containerPort: 7474  # HTTP
        - containerPort: 7687  # Bolt
        env:
        - name: NEO4J_AUTH
          value: neo4j/testpassword
        - name: NEO4J_dbms_memory_heap_initial__size
          value: 512M
        - name: NEO4J_dbms_memory_heap_max__size
          value: 1G
        - name: NEO4J_server_config_strict__validation_enabled
          value: "false"
        resources:
          limits:
            cpu: "2"
            memory: "4Gi"
          requests:
            cpu: "100m"
            memory: "256Mi"
        volumeMounts:
        - name: neo4j-data
          mountPath: /var/lib/neo4j/data
      volumes:
      - name: neo4j-data
        persistentVolumeClaim:
          claimName: neo4j-data